In [10]:
import numpy
import math
import cairo

row = 10
col = 10
map = [[0 for _ in range(row)] for _ in range(col)]

count = -1
for i in range(row):
    #count = -1
    for j in range(col):
        count = count + 1
        map[i][j] = 0
    print(map[i])
    
pos_x = 0
pos_y = 0

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [43]:
print(map[9][1])

91


In [50]:
import random as rd

coord = rd.choices(range(128,255),k=2)

print(coord)

[184, 231]


In [1]:
# Source - https://stackoverflow.com/a/10031877
# Posted by Sven Marnach, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-08, License - CC BY-SA 3.0

import numpy
import cairo
import math
import random as rd

width = 256 # map will always be a square, so only one dimension is needed

coord = rd.choices(range(int(width/2), int(width-1)), k=2)

data = numpy.zeros((width, width, 4), dtype=numpy.uint8)
surface = cairo.ImageSurface.create_for_data(
    data, cairo.FORMAT_ARGB32, width, width)
cr = cairo.Context(surface)

# fill with solid white

cr.set_source_rgb(1.0, 1.0, 1.0)
cr.paint()

# draw green radius (outer zone)
print("Generating green zone...")
cr.arc(coord[0], coord[1], width/4, 0, 2*math.pi) #arc(xcoord, ycoord, radius, ??, circle)
cr.set_source_rgb(0.0, 1.0, 0.0) #green
cr.fill()

for i in range(width):
    for j in range(width):
        if data[i,j,0] < 128:
            data[i,j,0] = 128

# draw yellow radius (middle zone)
print("Generating yellow zone...")
cr.arc(coord[0], coord[1], width/7, 0, 2*math.pi) 
cr.set_source_rgb(1.0, 1.0, 0.0) #yellow
cr.fill()

for i in range(width):
    for j in range(width):
        if data[i,j,0] < 64:
            data[i,j,0] = 64
            
# draw red radius (inner zone)
print("Generating red zone...")
cr.arc(coord[0], coord[1], width/25, 0, 2*math.pi) 
cr.set_source_rgb(1.0, 0.0, 0.0) #red
cr.fill()

for i in range(width):
    for j in range(width):
        if data[i,j,0] < 32:
            data[i,j,0] = 32

# draw dig radius
print("Generating dig zone...")
cr.arc(coord[0], coord[1], 2, 0, 2*math.pi) 
cr.set_source_rgb(0.0, 0.0, 0.0) # black
cr.fill()

# write output
print(coord)
print(data[(coord[1]-8):(coord[1]+8), (coord[0]-7):(coord[0]+7), 0])
surface.write_to_png("circle_complete_2.png")

Generating green zone...
Generating yellow zone...
Generating red zone...
Generating dig zone...
[159, 225]
[[32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 22  3  3 22 32 32 32 32 32]
 [32 32 32 32 32  3  0  0  3 32 32 32 32 32]
 [32 32 32 32 32  3  0  0  3 32 32 32 32 32]
 [32 32 32 32 32 22  3  3 22 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]
 [32 32 32 32 32 32 32 32 32 32 32 32 32 32]]
